// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qowjopwphgwgoyrszfqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvd2pvcHdwaGd3Z295cnN6ZnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODAyNzYsImV4cCI6MjA2NDc1NjI3Nn0.k1QGbB7uP4OHt5E9mf_QPHtB2L1h65xzDpjZgJt4X6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);